name: github-repo-stats

on:
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@HEAD
        with:
          ghtoken: ${{ secrets.ghrs_github_api_token }}

